###########
# site.title

title: Anantha Narayanan Suresh Babu
description: PhD Candidate & MathWorks Fellow | MIT CSE-MechE
baseurl: "" 
url: "https://www.anantha.me" # the base hostname & protocol for your site
permalink: pretty
# host: 0.0.0.0


#########################
# more settings

#permalink: /:title/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag 

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: false
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /:slug/
timezone: America/New_York
future: false

exclude:
- README.md
- LICENSE.md
- vendor

#exclude: [vendor]

Projects: /projects/

#Blog: /blog

# Add general links to site pages here
links:
  CV: /assets/Anantha_CV_2025_08.pdf
  Google Scholar: https://scholar.google.co.in/citations?user=OitRjjYAAAAJ&hl=en
  LinkedIn: https://www.linkedin.com/in/anantha-narayanan-suresh-babu-1038b5137/
  

# Add links for more focus here
#special_links:
#  "Search": https://duckduckgo.com